### ISSUE TITLE
"plugin:es-x/restrict-to-es2022" include from v0.23.0/language/es2022.json is missing.

### ISSUE THREAD

**Issue by sunafterrainwm** [wikimedia/jscs-preset-wikimedia#481] opened 2022-12-21 12:36 UTC
**Steps to replicate the issue** (include links if applicable):
* Install v0.23.0
* Write the following in .eslintrc.json:
```json
{
	"extends": [
		"wikimedia/language/es2022"
	]
}
```
* run `eslint <any-file>`

**What happens?**:
```
Oops! Something went wrong! :(

ESLint: 8.28.0

ESLint couldn't find the config "plugin:es-x/restrict-to-es2022" to extend from. Please check that the name of the config is correct.

The config "plugin:es-x/restrict-to-es2022" was referenced from the config file in "node_modules/.pnpm/eslint-config-wikimedia@0.23.0/node_modules/eslint-config-wikimedia/language/es2022.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

The eslint-plugin-es-x version bundled with 0.23.0 is ^5.2.1, but "plugin:es-x/restrict-to-es2022" cannot be found from [5.2.1](https://github.com/eslint-community/eslint-plugin-es-x/tree/v5.2.1/lib/configs) to the latest released [5.4.0](https://github.com/eslint-community/eslint-plugin-es-x/tree/v5.4.0/lib/configs)

**Comment by edg2s** [comment] 2023-01-17 11:30
Duplicate of #479

**Closed as completed by edg2s** 2023-01-17 11:30 UTC
