### ISSUE TITLE
warn when using JSDuck-only docblock tags

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia/jscs-preset-wikimedia#597] opened 2024-12-04 09:24 UTC
There are certain docblock tags that occur in JSDuck but not in JSDoc. Now that we are [mostly done with converting our codebases from JSDuck to JSDoc](https://phabricator.wikimedia.org/T138401), it might make sense to warn or error when these JSDuck-only docblock tags are encountered. Adding a rule for this will 1) keep them from creeping back into our codebase, and 2) draw people's attention to them so they can be refactored. They are...

```
* @accessor
* @alternateClassName
* @aside
* @cfg
* @docauthor
* @evented
* @experimental
* @ftype
* @hide
* @img
* @inheritable
* @localdoc
* @markdown
* @mixins
* @new
* @preventable
* @ptype
* @removed
* @singleton
* @template
* @uses
* @video
* @xtype
```

Examples:

<img width="598" alt="image" src="https://github.com/user-attachments/assets/feb074fd-b643-4c27-8ef7-0f80dcd1677f">

<img width="595" alt="image" src="https://github.com/user-attachments/assets/a60af47a-6e17-44e4-af31-f48b2f04dcd6">

**Comment by NovemLinguae** [comment] 2024-12-04 09:34
Partially overlaps with #299. This ticket has more tags though.

**Comment by edg2s** [comment] 2024-12-04 17:52
Duplicate of #299. Merged missing info into there.

**Closed as completed by edg2s** 2024-12-04 17:52 UTC
